syntax="proto3";

package notification;

service notificationService{
    rpc sendGlobalNotification(SendGlobalNotificationRequest) returns (NotificationResponse);
    rpc sendUserNotification(SendUserNotification) returns (NotificationResponse);
}

message SendGlobalNotificationRequest{
    string title=1;
    string body =2;
    string sender=3 ; //eg. user or admin.
}

message SendUserNotification{
    string user_id=1;
    string title=2;
    string body=3;
    string sender=4;
}

message NotificationResponse{
    string message =1;
    bool success=2;
}