syntax = "proto3";

package post;

service PostService {
    rpc AllPosts(Empty)returns (PostList);
    rpc ReportedPosts(Empty) returns (PostList);
    rpc FlagPost(FlagPostRequest) returns (PostResponse);
    rpc AdminDeletePost(PostIdRequest) returns (PostResponse);
}

message Empty{}

message Post {
  string id = 1;
  string userId = 2;
  string content = 3;
  repeated string media = 4;
  string visibility = 5;
  bool deleted = 6;
  bool moderated = 7;
  repeated string keywords = 8;
  string createdAt = 9;
  string updatedAt = 10;
  bool isReported = 11;
  string reportReason = 12;
}

message PostList{
    repeated Post posts=1;
}

message PostResponse{
    Post post =1;
}

message FlagPostRequest{
    string postId=1;
    string reason=2;
}

message PostIdRequest{
    string postId=1;
}